source 'https://rubygems.org'
ruby '2.2.1'

gem 'sinatra', '~> 1.4'
gem 'slim', '~> 2.1'
gem 'sass', '~> 3.4'
gem 'sinatra-partial', '~> 0.4'
gem 'multi_json', '~> 1.10'
gem 'unicorn', '~> 4.8'
gem 'activesupport', '~> 4.1'
